name: Slither Analysis

on: [ push ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - run: pip3 install crytic-compile
      - name: Run Slither
        uses: crytic/slither-action@v0.1.0
        id: slither
        continue-on-error: true
        with:
          sarif: results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}