name: Unit Tests

on: [push]

jobs:
  unit-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - run: npm install
      - run: cp config.sample.ts config.ts
      - run: npx hardhat compile
      - run: npx hardhat test
  name: Slither Analysis
  on: [ push ]
  jobs:
    analyze:
      runs-on: ubuntu-latest
      steps:
        - name: Run Slither
          uses: crytic/slither-action@v0.1.0
          id: slither
          continue-on-error: true
          with:
            sarif: results.sarif

        - name: Upload SARIF file
          uses: github/codeql-action/upload-sarif@v1
          with:
            sarif_file: ${{ steps.slither.outputs.sarif }}