name: Unit Tests

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - run: npm install
      - run: cp config.sample.ts config.ts
      - run: npx hardhat compile

  unit-tests:
    runs-on: ubuntu-latest
    needs: [compile]
    steps:
      - run: npx hardhat test